# Generated by Django 4.2.11 on 2025-10-25 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("study", "Bible Study"),
                            ("youth", "Youth Event"),
                            ("ministry", "Ministry"),
                            ("community", "Community"),
                            ("special", "Special Event"),
                            ("other", "Other"),
                        ],
                        default="service",
                        max_length=50,
                    ),
                ),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("requires_registration", models.BooleanField(default=False)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("max_attendees", models.IntegerField(blank=True, null=True)),
                ("registration_form", models.JSONField(blank=True, default=dict)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("recurrence_end_date", models.DateField(blank=True, null=True)),
                ("attendees", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "event_registrations",
                "ordering": ["-created_at"],
                "unique_together": {("event", "member")},
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="events_date_e70fc0_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["type"], name="events_type_671f92_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_recurring"], name="events_is_recu_2c3b4f_idx"
            ),
        ),
    ]
