# Generated by Django 4.2.11 on 2025-10-25 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("surname", models.CharField(blank=True, max_length=100)),
                ("other_names", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("telephone_home", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("postal_address", models.CharField(blank=True, max_length=255)),
                ("residential_house_no", models.CharField(blank=True, max_length=100)),
                ("community", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=255)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("place_of_birth", models.CharField(blank=True, max_length=200)),
                ("home_town", models.CharField(blank=True, max_length=200)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("id_type", models.CharField(blank=True, max_length=50)),
                ("id_no", models.CharField(blank=True, max_length=100)),
                ("occupational_status", models.CharField(blank=True, max_length=100)),
                ("profession", models.CharField(blank=True, max_length=200)),
                ("place_of_work", models.CharField(blank=True, max_length=255)),
                ("name_of_jhs", models.CharField(blank=True, max_length=255)),
                ("jhs_completion_year", models.CharField(blank=True, max_length=4)),
                ("name_of_shs", models.CharField(blank=True, max_length=255)),
                ("shs_completion_year", models.CharField(blank=True, max_length=4)),
                ("name_of_tertiary", models.CharField(blank=True, max_length=255)),
                (
                    "tertiary_completion_year",
                    models.CharField(blank=True, max_length=4),
                ),
                ("father_guardian_name", models.CharField(blank=True, max_length=255)),
                ("father_catholic", models.BooleanField(default=False)),
                ("father_parish", models.CharField(blank=True, max_length=255)),
                ("mother_guardian_name", models.CharField(blank=True, max_length=255)),
                ("mother_catholic", models.BooleanField(default=False)),
                ("mother_parish", models.CharField(blank=True, max_length=255)),
                ("membership_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("family_members", models.JSONField(blank=True, default=list)),
                ("children", models.JSONField(blank=True, default=list)),
                ("sacraments", models.JSONField(blank=True, default=dict)),
                (
                    "denomination_specific_data",
                    models.JSONField(blank=True, default=dict),
                ),
                ("others", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("last_activity_date", models.DateTimeField(blank=True, null=True)),
                ("engagement_score", models.IntegerField(default=0)),
                (
                    "total_giving",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_volunteer_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("ministries_count", models.IntegerField(default=0)),
                ("events_attended", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "members",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="MemberWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("baptism", "Baptism"),
                            ("confirmation", "Confirmation"),
                            ("membership", "Membership"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("steps", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "member_workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("marital_status", models.CharField(max_length=20)),
                ("occupation", models.CharField(blank=True, max_length=255)),
                ("emergency_contact", models.JSONField(default=dict)),
                ("church_experience", models.TextField()),
                ("reason_for_joining", models.TextField()),
                ("how_did_you_hear", models.TextField()),
                ("special_needs", models.TextField(blank=True)),
                ("skills", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "member_requests",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["member_id"], name="members_member__12a4b3_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["email"], name="members_email_d65d03_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["status"], name="members_status_e4ea77_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["last_name", "first_name"], name="members_last_na_ac5ab0_idx"
            ),
        ),
    ]
