# Generated by Django 4.2.11 on 2025-12-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberrequest",
            name="church",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_requests",
                to="churches.church",
            ),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_requests",
                related_query_name="confirmed_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="created_member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_request",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="created_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_member_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="memberrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Initial Review"),
                    ("approved", "Approved - Awaiting Final Confirmation"),
                    ("confirmed", "Confirmed - Member Account Created"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="memberrequest",
            index=models.Index(
                fields=["church", "status"], name="member_requ_church__b74c81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrequest",
            index=models.Index(fields=["status"], name="member_requ_status_6b20b7_idx"),
        ),
        migrations.AddIndex(
            model_name="memberrequest",
            index=models.Index(fields=["email"], name="member_requ_email_8bffff_idx"),
        ),
    ]
