"""
Denomination service for managing denomination-specific features.
Moved from frontend denominationDefaults.ts
"""


class DenominationService:
    """
    Service for managing denomination-specific features and defaults.
    This logic was previously on the frontend - now centralized on backend.
    """
    
    @staticmethod
    def get_denomination_defaults(denomination):
        """
        Get feature defaults for a denomination.
        
        Returns a dictionary of features with boolean values.
        """
        denom = (denomination or '').lower()
        
        defaults = {
            'catholic': {
                'sacraments': True,
                'tithing': False,
                'offerings': True,
                'liturgicalCalendar': True,
                'smallGroups': True,
                'events': True,
                'announcements': True,
                'certificates': True,
                'reconciliation': True,
                'anointingOfSick': True,
                'holyOrders': True,
                'serviceRequests': True,
                'pastoralNotes': True,
                'documents': True,
                'altarCalls': False,
                'prayerRequests': False,
                'pledges': False,
                'volunteerManagement': True,
                'sabbathScheduling': False,
                'healthMinistries': False,
                'elderRoles': False,
                'sessionNotes': False,
                'membershipWorkflows': False,
            },
            'anglican': {
                'sacraments': True,
                'tithing': False,
                'offerings': True,
                'liturgicalCalendar': True,
                'smallGroups': False,
                'events': True,
                'announcements': True,
                'certificates': True,
                'reconciliation': False,
                'anointingOfSick': False,
                'holyOrders': False,
                'serviceRequests': True,
                'pastoralNotes': True,
                'documents': True,
                'altarCalls': False,
                'prayerRequests': False,
                'pledges': False,
                'volunteerManagement': True,
                'sabbathScheduling': False,
                'healthMinistries': False,
                'elderRoles': False,
                'sessionNotes': False,
                'membershipWorkflows': False,
            },
            'pentecostal': {
                'sacraments': False,
                'tithing': True,
                'offerings': True,
                'liturgicalCalendar': False,
                'smallGroups': True,
                'events': True,
                'announcements': True,
                'certificates': False,
                'reconciliation': False,
                'anointingOfSick': False,
                'holyOrders': False,
                'serviceRequests': True,
                'pastoralNotes': True,
                'documents': False,
                'altarCalls': True,
                'prayerRequests': True,
                'pledges': False,
                'volunteerManagement': True,
                'sabbathScheduling': False,
                'healthMinistries': False,
                'elderRoles': True,
                'sessionNotes': False,
                'membershipWorkflows': True,
            },
            'baptist': {
                'sacraments': True,
                'tithing': True,
                'offerings': True,
                'liturgicalCalendar': False,
                'smallGroups': True,
                'events': True,
                'announcements': True,
                'certificates': False,
                'reconciliation': False,
                'anointingOfSick': False,
                'holyOrders': False,
                'serviceRequests': True,
                'pastoralNotes': True,
                'documents': True,
                'altarCalls': False,
                'prayerRequests': False,
                'pledges': False,
                'volunteerManagement': True,
                'sabbathScheduling': False,
                'healthMinistries': False,
                'elderRoles': False,
                'sessionNotes': False,
                'membershipWorkflows': True,
            },
            'presbyterian': {
                'sacraments': True,
                'tithing': False,
                'offerings': True,
                'liturgicalCalendar': False,
                'smallGroups': False,
                'events': True,
                'announcements': True,
                'certificates': False,
                'reconciliation': False,
                'anointingOfSick': False,
                'holyOrders': False,
                'serviceRequests': True,
                'pastoralNotes': True,
                'documents': False,
                'altarCalls': False,
                'prayerRequests': False,
                'pledges': False,
                'volunteerManagement': True,
                'sabbathScheduling': False,
                'healthMinistries': False,
                'elderRoles': True,
                'sessionNotes': True,
                'membershipWorkflows': True,
            },
            'methodist': {
                'sacraments': True,
                'tithing': False,
                'offerings': True,
                'liturgicalCalendar': False,
                'smallGroups': True,
                'events': True,
                'announcements': True,
                'certificates': False,
                'reconciliation': False,
                'anointingOfSick': False,
                'holyOrders': False,
                'serviceRequests': True,
                'pastoralNotes': True,
                'documents': False,
                'altarCalls': False,
                'prayerRequests': False,
                'pledges': True,
                'volunteerManagement': True,
                'sabbathScheduling': False,
                'healthMinistries': False,
                'elderRoles': False,
                'sessionNotes': False,
                'membershipWorkflows': True,
            },
            'seventh-day adventist': {
                'sacraments': True,
                'tithing': False,
                'offerings': True,
                'liturgicalCalendar': False,
                'smallGroups': False,
                'events': True,
                'announcements': True,
                'certificates': False,
                'reconciliation': False,
                'anointingOfSick': False,
                'holyOrders': False,
                'serviceRequests': True,
                'pastoralNotes': True,
                'documents': False,
                'altarCalls': False,
                'prayerRequests': False,
                'pledges': False,
                'volunteerManagement': True,
                'sabbathScheduling': True,
                'healthMinistries': True,
                'elderRoles': False,
                'sessionNotes': False,
                'membershipWorkflows': True,
            },
        }
        
        # Return defaults for denomination or generic defaults
        return defaults.get(denom, {
            'sacraments': False,
            'tithing': True,
            'offerings': True,
            'liturgicalCalendar': False,
            'smallGroups': True,
            'events': True,
            'announcements': True,
            'certificates': False,
            'reconciliation': False,
            'anointingOfSick': False,
            'holyOrders': False,
            'serviceRequests': True,
            'pastoralNotes': True,
            'documents': False,
            'altarCalls': False,
            'prayerRequests': False,
            'pledges': False,
            'volunteerManagement': True,
            'sabbathScheduling': False,
            'healthMinistries': False,
            'elderRoles': False,
            'sessionNotes': False,
            'membershipWorkflows': True,
        })
    
    @staticmethod
    def apply_defaults_to_church(church):
        """
        Apply denomination defaults to a church.
        """
        defaults = DenominationService.get_denomination_defaults(church.denomination)
        church.features = {**defaults, **church.features}
        church.save()
        return church

