# Generated by Django 4.2.11 on 2025-12-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="bypass_subscription_check",
            field=models.BooleanField(
                default=False,
                help_text="If True, this church bypasses all subscription/trial expiration checks. Use for testing or special cases.",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="grace_period_days",
            field=models.IntegerField(
                default=7, help_text="Days after expiration before blocking access"
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="church",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="church",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="church",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
