# Generated by Django 4.2.11 on 2025-12-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0002_church_bypass_subscription_check_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "paystack_reference",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("authorization_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paystack_response", models.JSONField(blank=True, default=dict)),
                ("subscription_activated", models.BooleanField(default=False)),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_payments",
                        to="churches.church",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["church", "status"],
                        name="subscriptio_church__0e53c0_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="subscriptio_referen_5683e4_idx"
                    ),
                    models.Index(
                        fields=["paystack_reference"],
                        name="subscriptio_paystac_f63455_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="subscriptio_status_c8a072_idx",
                    ),
                ],
            },
        ),
    ]
