# Generated by Django 4.2.11 on 2025-10-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("urgent", "Urgent"),
                            ("celebration", "Celebration"),
                            ("cancellation", "Cancellation"),
                            ("schedule_change", "Schedule Change"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Members"),
                            ("members", "Members Only"),
                            ("youth", "Youth"),
                            ("children", "Children"),
                            ("leaders", "Leaders"),
                            ("specific", "Specific Group"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "announcements",
                "ordering": ["-created_at"],
            },
        ),
    ]
