# Generated by Django 4.2.11 on 2025-10-25 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("worship", "Worship"),
                            ("youth", "Youth"),
                            ("children", "Children"),
                            ("prayer", "Prayer"),
                            ("outreach", "Outreach"),
                            ("pastoral", "Pastoral"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("meeting_schedule", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("max_capacity", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ministries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_ministries",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ministries",
                "db_table": "ministries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MinistryMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("leader", "Leader"),
                            ("assistant", "Assistant"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ministries.ministry",
                    ),
                ),
            ],
            options={
                "db_table": "ministry_memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("ministry", "member")},
            },
        ),
        migrations.AddField(
            model_name="ministry",
            name="members",
            field=models.ManyToManyField(
                related_name="ministries",
                through="ministries.MinistryMembership",
                to="members.member",
            ),
        ),
    ]
