# Generated by Django 4.2.11 on 2025-10-25 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_name", models.CharField(blank=True, max_length=255)),
                ("requester_email", models.EmailField(blank=True, max_length=254)),
                ("requester_phone", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("healing", "Healing"),
                            ("family", "Family"),
                            ("financial", "Financial"),
                            ("spiritual", "Spiritual"),
                            ("guidance", "Guidance"),
                            ("thanksgiving", "Thanksgiving"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_confidential", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("praying", "Praying"),
                            ("answered", "Answered"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("prayer_team_members", models.JSONField(blank=True, default=list)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("answer_testimony", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_prayers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_requests",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "prayer_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="prayer_requ_status_0bfee3_idx"
                    ),
                    models.Index(
                        fields=["category"], name="prayer_requ_categor_83f017_idx"
                    ),
                    models.Index(
                        fields=["urgency"], name="prayer_requ_urgency_ed2a43_idx"
                    ),
                ],
            },
        ),
    ]
