# Generated by Django 4.2.11 on 2025-10-25 22:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "pledges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(db_index=True)),
                ("receipt_number", models.CharField(max_length=100, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_ids", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_path", models.CharField(blank=True, max_length=500)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_receipts",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "tax_receipts",
                "ordering": ["-fiscal_year"],
                "unique_together": {("member", "fiscal_year")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tithe", "Tithe"),
                            ("offering", "Offering"),
                            ("pledge", "Pledge"),
                            ("donation", "Donation"),
                            ("building_fund", "Building Fund"),
                            ("mission", "Mission"),
                            ("special", "Special Offering"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("online", "Online"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("date", models.DateTimeField(db_index=True)),
                ("pledge_id", models.CharField(blank=True, max_length=100)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurring_frequency", models.CharField(blank=True, max_length=20)),
                ("recurring_end_date", models.DateField(blank=True, null=True)),
                ("fiscal_year", models.IntegerField(blank=True, null=True)),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_tax_deductible", models.BooleanField(default=True)),
                ("receipt_issued", models.BooleanField(default=False)),
                ("receipt_issued_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["member", "date"], name="payments_member__7c0bf3_idx"
                    ),
                    models.Index(
                        fields=["fiscal_year"], name="payments_fiscal__e78210_idx"
                    ),
                    models.Index(fields=["type"], name="payments_type_b6c23f_idx"),
                    models.Index(
                        fields=["reference"], name="payments_referen_2b1f06_idx"
                    ),
                ],
            },
        ),
    ]
