# Generated by Django 4.2.11 on 2025-10-25 22:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ministries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ministry", "Ministry"),
                            ("event", "Event"),
                            ("community", "Community"),
                            ("administration", "Administration"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("recurring", "Recurring"),
                            ("flexible", "Flexible"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("recurrence_pattern", models.CharField(blank=True, max_length=20)),
                ("spots_available", models.IntegerField(blank=True, null=True)),
                ("spots_filled", models.IntegerField(default=0)),
                ("requirements", models.TextField(blank=True)),
                ("hours_per_week", models.IntegerField(blank=True, null=True)),
                (
                    "commitment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("short_term", "Short Term"),
                            ("long_term", "Long Term"),
                            ("ongoing", "Ongoing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volunteer_opportunities",
                        to="ministries.ministry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Volunteer opportunities",
                "db_table": "volunteer_opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "hours_completed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("signup_date", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_signups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_signups",
                        to="members.member",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="volunteers.volunteeropportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_signups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_signups",
                "ordering": ["-signup_date"],
                "unique_together": {("opportunity", "member")},
            },
        ),
        migrations.CreateModel(
            name="VolunteerHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_hours",
                        to="members.member",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logged_hours",
                        to="volunteers.volunteeropportunity",
                    ),
                ),
                (
                    "signup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logged_hours",
                        to="volunteers.volunteersignup",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_hours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Volunteer hours",
                "db_table": "volunteer_hours",
                "ordering": ["-date"],
            },
        ),
    ]
