# Generated by Django 4.2.11 on 2025-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="church",
        ),
        migrations.AddField(
            model_name="theme",
            name="church_id",
            field=models.BigIntegerField(
                db_index=True,
                default=0,
                help_text="ID of the church this theme belongs to",
            ),
        ),
    ]
