# Generated by Django 4.2.11 on 2025-10-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AltarCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("sunday_service", "Sunday Service"),
                            ("midweek_service", "Midweek Service"),
                            ("special_event", "Special Event"),
                            ("revival", "Revival"),
                            ("crusade", "Crusade"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("salvation", "Salvation"),
                            ("rededication", "Rededication"),
                            ("healing", "Healing"),
                            ("baptism", "Baptism"),
                            ("deliverance", "Deliverance"),
                            ("ministry", "Ministry Call"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=True)),
                (
                    "follow_up_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("follow_up_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "altar_calls",
                "ordering": ["-service_date", "-created_at"],
            },
        ),
    ]
