# Generated by Django 4.2.11 on 2025-10-25 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("altarcalls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="altarcall",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_altar_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="altarcall",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="altar_calls",
                to="members.member",
            ),
        ),
        migrations.AddIndex(
            model_name="altarcall",
            index=models.Index(
                fields=["service_date"], name="altar_calls_service_895616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="altarcall",
            index=models.Index(fields=["reason"], name="altar_calls_reason_758c75_idx"),
        ),
        migrations.AddIndex(
            model_name="altarcall",
            index=models.Index(
                fields=["follow_up_status"], name="altar_calls_follow__df2037_idx"
            ),
        ),
    ]
